Billyzou0741326/bilibili-live-monitor-ts

build/bilibili/bilibili.js, build/danmu/builder.js, build/danmu/tcp-controller.js, build/danmu/tcp-danmu.js, build/global/config.js, build/task/task.js, src/bilibili/bilibili.ts, src/danmu/builder.ts, src/danmu/tcp-controller.ts, src/danmu/tcp-danmu.ts, src/global/config.ts, src/task/task.ts
- Silence TCP Errors
- Bug fix: Incomplete room list obtained from API
- Adjust room closed history clearing logic
=> 01-26-2020

Dockerfile, README.md, build/bilibili/account.js, build/bilibili/bilibili.js, build/bilibili/index.js, build/danmu/tcp-danmu.js, package.json, src/bilibili/account.ts, src/bilibili/bilibili.ts, src/bilibili/index.ts, src/danmu/builder.ts, src/danmu/tcp-danmu.ts
- Perpares to support client side operations
=> 02-11-2020

build/net/httperror.js, build/net/xhr.js, src/net/httperror.ts, src/net/xhr.ts
- Fixes HttpError's extension issue
=> 02-12-2020

build/async/index.js, build/async/sleep.js, build/bilibili/bilibili.js, build/db/database.js, src/async/index.ts, src/async/sleep.ts, src/bilibili/bilibili.ts, src/db/database.ts
- Fixes db, adds sleep
- Adds more client side operations
=> 02-14-2020

README.md, build/global/config.js, build/server/ws-server.js, build/settings.json, src/global/config.ts, src/server/ws-server.ts, src/settings.json
This was originally a PR from master branch. As Billy commented, we will leave this one open for now.
Copied from original PR #18 :
Billyzou0741326 commented 5 hours ago
I'm quite hesitant to use url-based authentication. What I have in mind is a full fledged per-user key authentication system stored in a database of some kind, the implementation of which is quite involved.
For now let's leave out the whole authentication part, and perhaps come back to it later.
blu3mania commented 31 seconds ago
Sure. In that case I will create a new feature branch and make a PR from there so we can leave it open. After that I will close this one and rebase my master branch back to the same as your HEAD commit.
=> Enhancement: optional user authentication support

build/bilibili/account.js, build/bilibili/bilibili.js, build/task/notifier.js, docs/_sidebar.md, docs/before-starting/README.md, docs/faq/README.md, src/bilibili/account.ts, src/bilibili/bilibili.ts, src/task/notifier.ts
- More client side operations
- Revise documentation
=> 02-21-2020

build/app/App.js, build/danmu/raffle.js, build/danmu/tcp-danmu.js, build/global/config.js, build/server/index.js, build/server/tcp-server.js, build/server/ws-server.js, build/settings.json, src/app/App.ts, src/danmu/raffle.ts, src/danmu/tcp-danmu.ts, src/global/config.ts, src/server/index.ts, src/server/tcp-server.ts, src/server/ws-server.ts, src/settings.json
- 对 [BiliHelper-Personal](https://github.com/lkeme/BiliHelper-personal) 进行对接 (无需key)
=> 02-24-2020

build/net/httperror.js, src/net/httperror.ts
- Conform to the best practice for extending Error
=> 02-26-2020

build/db/database.js, src/db/database.ts
- Filters out expired rooms on saving to database
=> 02-27-2020

build/db/database.js, src/db/database.ts
- Time calculation in incorrect unit
=> 02-29-2020

build/app/App.js, build/db/database.js, src/app/App.ts, src/db/database.ts, src/global/config.ts
Also improved performance by only loading database file once during startup. It still allows replacement of the db file during execution by monitoring the file.
Added graceful shutdown when CTRL-C is pressed.
Added access modifiers in config.ts which were missed in last commit.
=> Fixed the issue that new fixed rooms are not saved, by not overwriting in-memory map with database file

build/app/App.js, build/db/database.js, src/app/App.ts, src/db/database.ts
- Resolves db issue
- Adds additional complexity
=> 03-02-2020

docs/before-starting/README.md, docs/faq/README.md
- Update Documentation, as per #35
=> 03-10-2020

build/bilibili/bilibili.js, src/bilibili/bilibili.ts
- Replace `/room/v1/Room/room_init` with `/xlive/web-room/v1/index/getInfoByRoom?room_id`
=> 03-22-2020

build/bilibili/bilibili.js, build/global/config.js, build/net/request.js, src/bilibili/bilibili.ts, src/global/config.ts, src/net/request.ts
- Refactors low level Request API
Simple testing, ex:
```javascript
// src/test.ts
import { Xhr, Request } from './net/index';
(async(): Promise<void> => {
try {
const xhr = new Xhr();
console.log((await xhr.request(Request.Builder()
.withHost('api.bilibili.com')
.withPath('/x/space/arc/search')
.withMethod(Request.GET)
.withParams({
'ps': 100,
'pn': 1,
'order': 'pubdate',
'jsonp': 'jsonp',
'mid': 8047632,
})
.build()
)).json());
}
catch (error) {
console.log(error);
}
})()
```
=> 03-27-2020

build/db/database.js, docs/_sidebar.md, docs/debug/README.md, src/db/database.ts
- Fixes db missing await statement
- Update documentation with info for debugging with chrome devtools
=> 03-29-2020

docs/executing/README.md, package.json
- Update `package.json`
- Update Documentation
=> 03-31-2020

build/app/App.js, build/bilibili/bilibili.js, build/danmu/tcp-controller.js, build/danmu/tcp-danmu.js, src/app/App.ts, src/bilibili/bilibili.ts, src/danmu/tcp-controller.ts, src/danmu/tcp-danmu.ts
=> 04-01-2020

README.md, build/app/App.js, build/danmu/gift-history.js, build/danmu/raffle.js, build/danmu/tcp-danmu.js, build/global/config.js, build/server/http-server.js, build/server/tcp-server.js, build/server/ws-server.js, build/settings.json, docs/README.md, docs/before-starting/README.md, docs/developer-reference/README.md, src/app/App.ts, src/danmu/gift-history.ts, src/danmu/raffle.ts, src/danmu/tcp-danmu.ts, src/global/config.ts, src/server/http-server.ts, src/server/tcp-server.ts, src/server/ws-server.ts, src/settings.json
- Updates Documentation
- Selectively enables needed broadcasting formats
- Adds `anchor` type to broadcast list
- Aligns ws broadcast format with http api
=> 04-03-2020

build/danmu/gift-history.js, build/danmu/room-collector.js, build/danmu/tcp-controller.js, build/danmu/tcp-danmu.js, package.json, src/danmu/gift-history.ts, src/danmu/room-collector.ts, src/danmu/tcp-controller.ts, src/danmu/tcp-danmu.ts
- Fix memory leak in FixedGuardMonitor
- Prefer async/await contruct over promise
=> 04-06-2020

build/danmu/tcp-danmu.js, src/danmu/tcp-danmu.ts
=> 04-10-2020

build/app/App.js, build/bilibili/account.js, build/bilibili/bilibili-base.js, build/danmu/room-collector.js, build/danmu/tcp-danmu.js, build/global/config.js, src/app/App.ts, src/bilibili/account.ts, src/bilibili/bilibili-base.ts, src/danmu/room-collector.ts, src/danmu/tcp-danmu.ts, src/global/config.ts
* Retrieves dynamic rooms from more sources #46 
* Strips duplicated filters
* Enables http keep-alive
=> 04-11-2020

build/app/App.js, build/bilibili/bilibili-base.js, build/bilibili/bilibili.js, build/danmu/index.js, build/danmu/raffle.js, build/danmu/raffle_test.js, build/danmu/room-crawler.js, build/danmu/roomid-handler.js, build/danmu/tcp-danmu.js, build/net/request.js, src/app/App.ts, src/bilibili/bilibili-base.ts, src/bilibili/bilibili.ts, src/danmu/index.ts, src/danmu/raffle.ts, src/danmu/raffle_test.ts, src/danmu/room-crawler.ts, src/danmu/roomid-handler.ts, src/danmu/tcp-danmu.ts, src/net/request.ts
- RoomidHandler fault tolerance
- Crawler done
=> 04-17-2020

build/app/App.js, build/bilibili/bilibili.js, build/client/index.js, build/client/tcp-client.js, build/danmu/room-crawler.js, build/danmu/roomid-handler.js, build/settings.json, docs/before-starting/README.md, src/app/App.ts, src/bilibili/bilibili.ts, src/client/index.ts, src/client/tcp-client.ts, src/danmu/room-crawler.ts, src/danmu/roomid-handler.ts, src/settings.json
- Matches lkeme
- Changes default strategy to forwarding
=> 04-18-2020
